package com.junerver.myblog.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.junerver.myblog.db.entity.ArticleEntity;

import com.junerver.myblog.db.dao.ArticleEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig articleEntityDaoConfig;

    private final ArticleEntityDao articleEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        articleEntityDaoConfig = daoConfigMap.get(ArticleEntityDao.class).clone();
        articleEntityDaoConfig.initIdentityScope(type);

        articleEntityDao = new ArticleEntityDao(articleEntityDaoConfig, this);

        registerDao(ArticleEntity.class, articleEntityDao);
    }
    
    public void clear() {
        articleEntityDaoConfig.getIdentityScope().clear();
    }

    public ArticleEntityDao getArticleEntityDao() {
        return articleEntityDao;
    }

}
